export const SITUATION_LABEL_BY_SLUG: Record<string, string> = {
  foreclosure: "Foreclosure",
  inherited: "Inherited house",
  divorce: "Divorce",
  tenants: "House with tenants",
  lien: "House with a lien",
  "water-damage": "Water / flood damage",
  "fire-damage": "Fire damage",
  "storm-damage": "Storm damage",
  "mold-damage": "Mold Damage",
  "as-is-florida": "Sell as-is Florida",
  "cash-home-buyers": "Cash home buyers",
  condemned: "Condemned house",
  "medical-emergency": "Medical emergency",
  "hoarder-house": "Hoarder house",
  "reverse-mortgage": "Reverse mortgage",
  "sell-as-is": "Sell as-is (St Pete)",
  bankruptcy: "Bankruptcy",
  "foundation-problems": "Foundation problems",
};
