/** Full section content for /sell-flooded-house-florida from situation-page/sell-flooded-house-st-petersburg.html */

export const WATER_DAMAGE_CONTENT = {
  hero: {
    formTitle: "Get a cash offer today.",
    formIntro:
      "Tell us about your flood-damaged St Petersburg home. We'll review it AS-IS and have a no-obligation offer in your hands quickly.",
    authorRole: "Local Founder · We Buy St Pete Houses · Pinellas County",
    addressPlaceholder: "123 Main St, St Petersburg FL",
    neighborhoodTags: ["Shore Acres", "Pinellas Point", "Old Northeast", "All St Pete Neighborhoods"],
    checklist: [
      "Cash offer — no obligation to accept",
      "Buy AS-IS — no repairs, no cleanup",
      "Close as fast as 7–14 days",
      "No realtor fees or commissions",
      "Local St Pete team — owner-operated",
    ],
  },
  stats: [
    { value: "24", suffix: "hrs", label: "To receive your cash offer" },
    { value: "7–14", label: "Days to close when ready" },
    { prefix: "$", value: "0", label: "Commissions or fees" },
    { value: "500", suffix: "+", label: "Homes purchased in St Pete" },
  ],
  sectionOrder: [
    "stats",
    "prose",
    "process",
    "cards",
    "comparison",
    "diff",
    "whyUs",
    "areas",
    "resources",
    "faq",
    "finalCta",
  ],
  prose: {
    eyebrow: "Cash Offer — Flood-Damaged Homes",
    titleLead: "Get a Cash Offer for Your ",
    titleEm: "Flood-Damaged St Pete Home",
    titleTail: "",
    lede: "Flood damage can feel overwhelming, but selling your St Pete home doesn't have to be. We offer a direct, transparent path to cash — no commissions, no hidden costs, and a flexible closing timeline that works around your needs.",
    paragraphs: [
      "We purchase flood-damaged properties in their current condition across St Petersburg and Pinellas County. You don't need to repair water damage, remediate mold, or stage the home before selling. We evaluate your property AS-IS and make a fair cash offer based on its current state.",
      "Our process is designed for sellers who need certainty. There's no obligation to accept our offer, no pressure to decide on a timeline you didn't choose, and no surprises at closing. The cash offer we present is what you receive — no deductions added later.",
      "Whether your home is in Shore Acres (which has seen significant flood impact following recent hurricanes), Pinellas Point, Old Northeast, or anywhere else in St Petersburg — we know the local landscape, the flood zones, and the community dynamics. That local expertise translates to faster, more confident offers.",
    ],
    sidebar: {
      title: "What Sellers Get from Us",
      items: [
        { strong: "Fair cash offer", text: "— based on your home's AS-IS condition, local market data, and comparable sales in St Pete." },
        { strong: "No obligation", text: "— review the offer at your own pace. If it doesn't work for you, no pressure." },
        { strong: "No fees or commissions", text: "— the offer we make is what you receive. Zero realtor fees, zero closing costs passed to you." },
        { strong: "Flexible closing", text: "— we work around your schedule, whether you need to move fast or need extra time." },
        { strong: "Full guidance", text: "— we walk you through every document and every step, keeping the process transparent and seller-friendly." },
      ],
    },
  },
  process: {
    eyebrow: "5-Step Process",
    titleLead: "How It Works When You Sell ",
    titleEm: "Flooded Property",
    titleTail: " to Us",
    lede: "Our process starts with your details, a no-obligation AS-IS review, and a cash offer with a closing timeline that fits you. Each step is transparent, seller-friendly, and built around your needs.",
    steps: [
      { num: "01", title: "Initial Contact", body: "Reach out by phone, email, or our online form. Tell us about your property — location, extent of the flood damage, and your preferred timeline. No formal inspection required." },
      { num: "02", title: "Property Review", body: "We evaluate your home based on the information you provide. No repairs required, no move-in condition needed. We're buying AS-IS and factor in real flood damage honestly." },
      { num: "03", title: "Cash Offer", body: "We present a fair cash offer — transparent, written, and based on current condition and local St Pete market data. You review it at your own pace with no obligation to accept." },
      { num: "04", title: "Flexible Closing Timeline", body: "Cash offers can close quickly. Some transactions complete in as little as a week to two weeks when conditions align. The exact timeline depends on your readiness and situation — we prioritize what works for you." },
      { num: "05", title: "Final Close and Transfer of Funds", body: "Once you're ready, we finalize the paperwork and transfer the cash. You walk away without repair costs, realtor fees, or drawn-out negotiations. We guide you through every document you need." },
    ],
    note: "What you'll typically need: Proof of ownership (deed or title), government-issued ID, and property details. Flood damage documentation is helpful but not required. Our team walks you through each step.",
    primaryCta: "Get my cash offer",
  },
  cards: {
    eyebrow: "Properties We Purchase",
    titleLead: "What We Buy and ",
    titleEm: "When It Applies",
    titleTail: "",
    lede: "We buy flood-damaged homes in St Pete regardless of mild-to-severe damage — AS-IS and fast. Whether your property has water stains or significant structural concerns, we're interested.",
    items: [
      { icon: "💧", title: "Flood-Damaged Properties", body: "Homes with water damage from hurricanes, storms, or rising water levels across St Petersburg and Pinellas County neighborhoods." },
      { icon: "🌊", title: "Flood Zone Properties", body: "Properties in established flood zones or areas with a history of water intrusion — including Shore Acres and other at-risk St Pete neighborhoods." },
      { icon: "🏠", title: "Mold and Moisture Damage", body: "Houses with mold growth, persistent moisture, compromised drywall, or water-damaged foundations. No remediation required before selling." },
      { icon: "🌀", title: "Combined Flood + Hurricane Damage", body: "Properties with combined water damage and wind or structural damage from hurricane events. We evaluate the whole picture and make one fair offer." },
      { icon: "🧱", title: "Compromised Foundations", body: "Structural concerns from flood saturation, settling, or slab damage. Traditional buyers walk away — we evaluate honestly and still make a fair offer." },
      { icon: "✓", title: "Any Flood Damage Condition", body: "Mild water stains to severe interior damage — we buy them all in St Petersburg. Contact us and let us evaluate your specific situation." },
    ],
    exclusionNote:
      "Condemned properties or structures with illegal builds. If your home is legally habitable and you hold clear title, we're interested — regardless of flood damage extent.",
  },
  comparison: {
    eyebrow: "Cash vs Traditional",
    titleLead: "Why Cash Offers Beat ",
    titleEm: "Traditional Realtors",
    titleTail: "",
    lede: "Cash offers remove financing delays, eliminate realtor commissions, and move faster. For flood-damaged homes specifically, these advantages become critical — traditional buyers and lenders often won't engage at all.",
    traditionalLabel: "Traditional Realtor",
    traditionalTimeline: "30–60+ days avg",
    cashLabel: "We Buy St Pete Houses",
    cashTimeline: "7–14 days",
    featuredBadge: "Best for flood damage",
    rows: [
      { label: "Purchase condition", traditional: "Repairs often required to list", cash: "AS-IS — no repairs required" },
      { label: "Realtor commissions", traditional: "Typical 5–6% of sale price", cash: "None" },
      { label: "Closing timeline", traditional: "Average 30–60+ days", cash: "As little as 7–14 days" },
      { label: "Financing contingencies", traditional: "Buyer financing adds risk & delay", cash: "None — cash purchase" },
      { label: "Lender flood zone requirements", traditional: "Often blocks sale entirely", cash: "Not applicable — no lender" },
      { label: "Offer transparency", traditional: "Negotiation, inspection credits, price drops", cash: "Flat cash offer — no hidden deductions" },
    ],
  },
  diff: {
    eyebrow: "Local Knowledge Advantage",
    titleLead: "Our Local Expertise and ",
    titleEm: "Speed Advantage",
    titleTail: "",
    lede: "Why does local expertise matter when selling a flood-damaged home? Because the nuances of St Pete's flood history, neighborhood dynamics, and market realities directly affect your offer — and distant investors don't know them.",
    items: [
      { num: "01", title: "Understanding St Pete's Flood History", body: "We know which neighborhoods have been impacted by recent hurricanes, where flood zones are most challenging, and how local market dynamics affect valuations. Shore Acres and similar areas have seen real price adjustments we factor in honestly — giving you a fair offer, not a lowball based on generic data." },
      { num: "02", title: "Speed to Close", body: "Because we operate locally and focus exclusively on St Petersburg, we move fast. We don't need to coordinate with distant investors or navigate unfamiliar markets. We know St Pete — and that translates to quicker decisions and smoother closings without the delays national buyers introduce." },
      { num: "03", title: "Owner-Operator Perspective", body: "We're not a faceless national chain. We're a local operation invested in this community, committed to treating sellers fairly, and accountable to our reputation here in St Pete. That local identity means we care about the outcome — not just the transaction." },
    ],
  },
  whyUs: {
    eyebrow: "Why Sellers Choose Us",
    titleLead: "Why Sellers Trust ",
    titleEm: "We Buy St Pete Houses",
    titleTail: "",
    lede: "Local focus, transparent process, no-obligation offers, and no fees. Here's exactly what makes us different from generic investors and national cash-offer chains.",
    items: [
      { title: "Local focus — St Petersburg specialists", body: "We specialize in St Petersburg and understand the unique challenges of selling flood-damaged homes in this specific market, including flood zones, neighborhood dynamics, and post-hurricane pricing realities." },
      { title: "Transparent process — no surprises", body: "We explain every step, from the initial offer to the final close. No surprise deductions, no bait-and-switch after acceptance, no hidden fees anywhere in the process." },
      { title: "No-obligation offers — you decide", body: "You review our cash offer on your terms. If it doesn't work for you, there's no pressure to accept and no cost for having explored the option. Zero obligation throughout." },
      { title: "No fees or commissions — keep more", body: "We don't charge realtor commissions or closing fees. The offer we make is what you receive — there's no percentage taken out at closing, no cost for our service." },
    ],
    asideTitle: "Ready to get a cash offer today?",
    asideBody: "Call or message us now. A local St Pete team member responds promptly with a no-obligation cash offer for your flood-damaged property.",
  },
  areas: {
    eyebrow: "Service Area",
    titleLead: "Areas We Serve in ",
    titleEm: "St Petersburg",
    titleTail: "",
    lede: "We buy houses across St Pete and the surrounding area. Our local focus means we know the flood zones, the neighborhood pricing dynamics, and the community landscape throughout Pinellas County.",
    areasNote:
      "Not sure if your property is within our area? Reach out anyway — we often work with sellers in adjacent communities.",
  },
  resources: {
    eyebrow: "Local & Government Resources",
    titleLead: "Local Resources for ",
    titleEm: "St Petersburg Sellers",
    titleTail: "",
    lede: "If you're dealing with flood damage, these local and federal resources can help with documentation, records, and disaster assistance — alongside our cash offer process.",
    items: [
      {
        tag: "City",
        title: "St. Petersburg City Hall",
        body: "General city services, permits, and local ordinances for properties within St. Petersburg city limits.",
        href: "https://www.stpete.org/",
        linkLabel: "stpete.org →",
      },
      {
        tag: "Property Records",
        title: "Pinellas County Property Appraiser",
        body: "Property valuations, tax assessments, and ownership records for all Pinellas County properties.",
        href: "https://www.pcpao.gov/",
        linkLabel: "pcpao.gov →",
      },
      {
        tag: "Court Records",
        title: "Pinellas County Clerk of the Circuit Court & Comptroller",
        body: "Official records, deeds, and court filings. Essential for confirming ownership before any sale transaction.",
        href: "https://www.pinellasclerk.org/",
        linkLabel: "pinellasclerk.org →",
      },
      {
        tag: "Federal",
        title: "FEMA Disaster Assistance",
        body: "Federal disaster assistance programs for flood recovery. Check eligibility for your St Petersburg property after a declared disaster.",
        href: "https://www.fema.gov/assistance/individual",
        linkLabel: "fema.gov/assistance →",
      },
      {
        tag: "State",
        title: "Florida Division of Emergency Management",
        body: "State-level disaster response and recovery resources. Coordinate with state programs alongside your selling options.",
        href: "https://www.floridadisaster.org/",
        linkLabel: "floridadisaster.org →",
      },
      {
        tag: "Cash Buyer",
        title: "We Buy St Pete Houses",
        body: "Local cash buyer specializing in flood-damaged properties across St Pete and Pinellas County. No repairs, no commissions, fast close.",
      },
    ],
  },
  faq: {
    eyebrow: "Common Questions",
    titleLead: "Common seller questions about ",
    titleEm: "flood-damaged homes",
    titleTail: " in St Petersburg.",
    items: [
      {
        q: "Is it hard to sell a house in a flood zone in St Petersburg?",
        a: "It can be challenging through traditional channels. Lenders often won't finance purchases in flood zones, and buyers requiring financing may be blocked entirely. A cash buyer eliminates this obstacle — we purchase directly without lender requirements, making flood zone properties fully sellable.",
      },
      {
        q: "Is selling a flooded house in St Petersburg feasible?",
        a: "Yes. We buy flood-damaged houses in St Petersburg for cash, AS-IS, with fast closes. You don't need to repair anything or wait for traditional buyer financing. We evaluate your property in its current condition and make a fair cash offer.",
      },
      {
        q: "How long does closing take on a flood-damaged home?",
        a: "Cash offers can close quickly. We've helped sellers close in as little as a week to two weeks when conditions align. The exact timeline depends on your readiness and situation — we prioritize speed and flexibility, and we work around your schedule.",
      },
      {
        q: "Do I need to repair before selling?",
        a: "No. We buy AS-IS, so repairs are not required for our cash offers. Whether your home has water stains, structural concerns, mold, or significant interior damage, we purchase it in its current state. You avoid the cost and hassle of repairs entirely.",
      },
      {
        q: "What documents are needed to start the sale?",
        a: "We'll gather property info and basic identification, and we'll guide you through every document you need. Typically, this includes proof of ownership, property details, and a few standard disclosures. Our team walks you through each step to make the process straightforward.",
      },
      {
        q: "Do you offer cash and are there fees?",
        a: "Yes, we offer cash for AS-IS properties. There are no commissions, and the process is transparent. The cash offer we make is what you receive — no hidden fees, no realtor commissions, no closing costs passed to you.",
      },
      {
        q: "Is this service available in surrounding areas of St Pete?",
        a: "We serve St Pete and nearby neighborhoods within Pinellas County, including Shore Acres, Pinellas Point, Old Northeast, Clearwater, Gulfport, Largo, and Pinellas Park. If your property is in or near St Petersburg, we're interested.",
      },
      {
        q: "What is the fastest way to start the sale today?",
        a: "Contact us to get a quick, no-obligation review and a cash-offer timeline that fits you. Reach out by phone, email, or our online form — share a few details about your flooded property and we'll respond promptly with next steps.",
      },
      {
        q: "How can I verify the trust signals shown for your service?",
        a: "We provide verifiable testimonials and transparent timelines, and you can request references. Our local reputation in St Petersburg matters to us — we're committed to demonstrating trustworthiness through clear communication and proven outcomes in this community.",
      },
    ],
  },
  finalCta: {
    eyebrow: "Ready to sell?",
    titleLead: "Sell your flooded St Pete home ",
    titleEm: "for cash today.",
    titleTail: "",
    description: "No repairs. No commissions. AS-IS cash offer with a closing timeline that works for you. Get started now — no obligation, no pressure.",
  },
};
